---
include:
  - board: xiao_ble
    shield: eyeslash_sofle_central_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_sofle_central_dongle
  - board: xiao_ble
    shield: eyeslash_sofle_peripheral_left nice_view_custom
  - board: xiao_ble
    shield: eyeslash_sofle_peripheral_right nice_view_custom
  - board: xiao_ble
    shield: settings_reset
