---
include:
  - board: nice_nano_v2
    shield: eyeslash_sofle_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_sofle_central_dongle_oled
  - board: nice_nano_v2
    shield: eyeslash_sofle_peripheral_left nice_oled
  - board: nice_nano_v2
    shield: eyeslash_sofle_peripheral_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset